add `cvmfs_remove_tags`

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -39,6 +39,14 @@ inputs:
         what CPU architecture platform to use when building the image
     default: "linux/amd64"
     required: false
+  cvmfs_remove_tags:
+    description: |
+      IF REMOVING ON CVMFS (else, var is ignored):
+        the image **TAGS** (i.e. 'bar' in 'baz/foo:bar') to remove on CVMFS -- newline-delimited
+        tags can be a pattern-based or verbatim -- see https://github.com/WIPACrepo/build-singularity-cvmfs-action
+      Ex: '\$\{{ github.ref_name }}-[SHA]'
+    default: ""
+    required: false
 
 
 runs:
@@ -138,14 +146,32 @@ runs:
     ####################################################################################
 
     - if: env.DO_1_CVMFS_REMOVE == 'true'
+      name: Determine CVMFS nametags to remove
+      env:
+        TAGS: ${{ inputs.cvmfs_remove_tags }}
+      run: |
+        # step: ???  # TODO: set `name` or `id` attr
+        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+        
+        if [[ -n "$TAGS" ]]; then
+            python3 -c 'import os; print("\n".join(f"{os.environ[\"IMAGE_NAME\"]}:{tag.strip()}" for tag in os.environ["TAGS"].splitlines() if tag.strip()))' > delete_image_nametags.txt
+        else
+            echo "::error::'inputs.cvmfs_remove_tags' (${{ inputs.cvmfs_remove_tags }}) must be given in order to remove CVMFS images"
+            exit 1
+        fi
+        
+        echo "DELETE_IMAGE_NAMETAGS<<EOF" >> "$GITHUB_ENV"
+        cat delete_image_nametags.txt >> "$GITHUB_ENV"
+        echo "EOF" >> "$GITHUB_ENV"
+      shell: bash
+
+    - if: env.DO_1_CVMFS_REMOVE == 'true'
       name: Request Removing Image(s) from CVMFS
       uses: WIPACrepo/build-singularity-cvmfs-action@v2.0
       with:
         github_token: ${{ inputs.github_token }}  # so job can git push
         dest_dir: ${{ inputs.cvmfs_dest_dir }}  # Required for constructing path pattern
-        delete_image_nametags: |
-          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-[SHA]
-        # ^^^ `[SHA]` corresponds to docker/metadata-action's `type=sha,prefix={{branch}}-` (ctrl+f)
+        delete_image_nametags: ${{ env.DELETE_IMAGE_NAMETAGS }}
 
 
     ####################################################################################
@@ -217,5 +243,5 @@ runs:
       uses: WIPACrepo/build-singularity-cvmfs-action@v2.0
       with:
         github_token: ${{ inputs.github_token }}  # so job can git push
-        dest_dir: ${{ inputs.cvmfs_dest_dir }}  # Required for constructing path pattern
+
         build_images: ${{ steps.docker_meta.outputs.tags }}
